language: python

python: 
  - 3.6
  - 3.7
  - 3.8
  - 3.9

branches:
  - main

before_script:
  - sudo apt-get install ffmpeg
  - pip install sync_dl_ytapi
  - pip install -e .

script:
  - python3 test.py https://www.youtube.com/playlist\?list\=PLbg8uA1JzGJD56Lfl7aYK4iW2vJHDo0DE